import type { Metadata } from 'next';
import { Geist_Mono, Quicksand } from 'next/font/google';
// import { Geist, Geist_Mono } from 'next/font/google';
import { Sidebar } from '@/components/Sidebar/Sidebar';
import './globals.css';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

const quicksand = Quicksand({
  variable: '--font-quicksand-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Make Cents',
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={[
          `${quicksand.variable} ${geistMono.variable} antialiased`,
          // `${geistSans.variable} ${geistMono.variable} antialiased`,
          'bg-neutral-300 dark:bg-neutral-700',
          'text-neutral-800 dark:text-neutral-200',
        ].join(' ')}
      >
        <div className='flex flex-row'>
          <Sidebar />
          <div id='app-content' className='grow'>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}

